### ISSUE TITLE
directory arg not recognized

### ISSUE THREAD

**Issue by jgrisafe** [pgrimaud/action-shopify#12]
Using the arg as mentioned in the readme: 

```
      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOP_ACCESS_TOKEN }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOP_STORE }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOP_PULL_THEME }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --directory=dist
```

Getting error: `unknown flag: --directory`
