### ISSUE TITLE
"No Such File Or Directory"

### ISSUE THREAD

**Issue by chryton** [pgrimaud/action-shopify#4]
I am seeing an issue where the shopify action is not able to find the checked out theme. Below is a slim example of the action file:

```yml
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy Shopify theme
        uses: pgrimaud/action-shopify@2.1.0
        env:
          SHOPIFY_PASSWORD: ${{ secrets.DEV_SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.DEV_SHOPIFY_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.DEV_SHOPIFY_THEME_ID }}
          THEME_PATH: /github/workspace
```
**Error:** `readAsset: open /github/workspace/***: no such file or directory`

Regardless if I use `/github/workspace`, `./`, `$GITHUB_WORKSPACE`, or `${{ github.workspace }}` for the `THEME_PATH` it appears that the theme is in accessible by the themekit instance.
