### ISSUE TITLE
Merging changes made on settings_data.json

### ISSUE THREAD

**Issue by maximilian** [pgrimaud/action-shopify#9]
Hello, we are having issues when making changes to the theme customizer.

Since settings_data.json is modified, we are having trouble merging the changes together, since Shopify is so picky about the formatting of settings_data.json. The deployment then fails because of this. 

What's the best way to approach this? We have thought of simply deploying it without settings_data.json and then making the required changes again on the theme deployed to.

Many thanks.

**Comment by pgrimaud** [comment]
Hello,

I always ignore settings_data.json file during deployment.

I made a PoC of Shopify development workflow using GitHub Actions with multiple environments here : https://github.com/freyum/shopify-workflow-poc

If you check one of the action file [here](https://github.com/freyum/shopify-workflow-poc/blob/master/.github/workflows/production.yml), you will see this : 

```yaml
...
jobs:
  deploy:
    name: Deploy Production Theme
    runs-on: ubuntu-latest
    steps:
      # basically git clone
      - uses: actions/checkout@v2
      # deploy shopify theme
      - uses: pgrimaud/action-shopify@2.1.0
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PRODUCTION_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_PRODUCTION_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_PRODUCTION_THEME_ID }}
          THEME_PATH: ${{ secrets.THEME_PATH }}
        with:
          args: --ignored-file=config/settings_data.json --ignored-file=locales/*
```

I set the `ignored-file` options on args to avoid config/settings_data.json file to be overridden.
